const dotenv = require("dotenv");
dotenv.config();

DATABASE_HOST = process.env.DATABASE_HOST;
DATABASE_USERNAME = process.env.DATABASE_USERNAME;
DATABASE_PASSWORD = process.env.DATABASE_PASSWORD;
DATABASE_NAME = process.env.DATABASE_NAME;
JWT_SECRET = process.env.JWT_SECRET;
POSITION_STACK_API_KEY = process.env.POSITION_STACK_API_KEY;
CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

module.exports = {
  DATABASE_HOST,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
  DATABASE_NAME,
  JWT_SECRET,
  POSITION_STACK_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
};
