//statuses
const SQL_DUPLICATE_ENTRY = "SQL_DUPLICATE_ENTRY";
const INVALID_PASSWORD = "INVALID_PASSWORD";
const INVALID_USERNAME = "INVALID_USERNAME";
const INVALID_EMAIL = "INVALID_EMAIL";
const DATA_NOT_PROVIDED = "DATA_NOT_PROVIDED";
const BAD_REQUEST = "BAD_REQUEST";
const INTERNAL_ERROR = "INTERNAL_ERROR";
const UNAUTHORIZED = "UNAUTHORIZED";
const NOT_FOUND = "NOT_FOUND";
const SUCCESS = "SUCCESS";
const CREATED = "CREATED";

//status codes
const INTERNAL_ERROR_CODE = 500;
const BAD_REQUEST_CODE = 400;
const UNAUTHORIZED_CODE = 401;
const NOT_FOUND_CODE = 404;
const SUCCESS_CODE = 200;
const CREATED_CODE = 201;

module.exports = {
  SQL_DUPLICATE_ENTRY,
  INVALID_PASSWORD,
  INVALID_USERNAME,
  INVALID_EMAIL,
  DATA_NOT_PROVIDED,
  BAD_REQUEST,
  INTERNAL_ERROR,
  UNAUTHORIZED,
  NOT_FOUND,
  SUCCESS,
  CREATED,
  INTERNAL_ERROR_CODE,
  BAD_REQUEST_CODE,
  UNAUTHORIZED_CODE,
  NOT_FOUND_CODE,
  SUCCESS_CODE,
  CREATED_CODE,
};
